import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Nanum_Gothic,
  Noto_Sans_KR,
} from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import LightDarkToggle from "@/components/common/light-dark-toggle";

const nanumGothic = Nanum_Gothic({
  variable: "--font-nanum-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // get dark mode cookie from server
  const darkModeCookie = (await cookies()).get("dark-mode")?.value;
  const isDarkMode = darkModeCookie === "true";

  return (
    <html lang="ko">
      <body
        className={`${nanumGothic.variable} ${notoSansKR.variable} ${
          isDarkMode ? "dark" : ""
        } antialiased relative`}
      >
        {children}
        <div className="absolute right-3 bottom-3">
          <LightDarkToggle />
        </div>
      </body>
    </html>
  );
}
